#!/bin/sh
PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

[ -f "/etc/default/ntbclient" ] && . /etc/default/ntbclient
case `echo "${USE_TPM}" | cut -c 1` in
    T|t|Y|y)
        TPM=true;;
    *)
        TPM=false;;
esac

[ -f "/etc/ntbclient/ntbclient.conf" ] && . /etc/ntbclient/ntbclient.conf

# ntbclient
if [ "${NTB}" != "n" ]; then

    if [ $(sed '/^$/d;/^#/d' "/etc/crypttab" | wc -l) = "0" ]; then
        echo "ntbclient: NOTICE: Skipping ntbclient installation because /etc/crypttab has no entries." >&2
        exit 0
    fi

    ntbclient_static="/usr/bin/ntbclient.static"
    if [ -x "/var/lib/ntbclient/ntbclient.static" ]; then
        echo "ntbclient: NOTICE: use /var/lib/ntbclient/ntbclient.static instead of ${ntbclient_static}" >&2
        ntbclient_static="/var/lib/ntbclient/ntbclient.static"
    fi

    if [ ! -x "${ntbclient_static}" ]; then
        echo "ntbclient: FAILURE: ${ntbclient_static} not found or not executable!" >&2
    fi

    if $TPM && [ ! -x "/usr/sbin/tcsd" ]; then
        echo "ntbclient: FAILURE: /usr/sbin/tcsd not found!" >&2
        exit 0
    fi

    if [ ! -f "${KEY_PATH}" ]; then
        echo "ntbclient: WARNING: \"${KEY_PATH}\" does not exist" >&2
    fi

    . /usr/share/initramfs-tools/hook-functions

    # Copy static ntbclient
    mkdir -p "${DESTDIR}/lib/ntbclient/"
    copy_exec "${ntbclient_static}" "/lib/ntbclient/ntbclient"

    # Conf for ntbclient
    rm -f ${DESTDIR}/etc/default/ntbclient
    mkdir -p ${DESTDIR}/etc/default
    cp /etc/default/ntbclient ${DESTDIR}/etc/default/ntbclient

    rm -f ${DESTDIR}/etc/ntbclient
    mkdir -p ${DESTDIR}/etc/ntbclient
    cp /etc/ntbclient/ntbclient.conf ${DESTDIR}/etc/ntbclient/ntbclient.conf

    rm -f ${DESTDIR}/usr/share/ntbclient
    mkdir -p ${DESTDIR}/usr/share/ntbclient
    cp /usr/share/ntbclient/ntbclient.conf.spec ${DESTDIR}/usr/share/ntbclient/ntbclient.conf.spec

    rm -f ${DESTDIR}/etc/ssl/certs/ca-certificates.crt
    mkdir -p ${DESTDIR}/etc/ssl/certs/
    cp /etc/ssl/certs/ca-certificates.crt ${DESTDIR}/etc/ssl/certs/ca-certificates.crt

    # Var for ntbclient
    for cache_file in "${cache_id_file}" "${ca_certificate_file}"
    do
        if [ -n "${cache_file}" ] && [ -f "${cache_file}" ]
        then
            rm -f "${DESTDIR}${cache_file}"
            mkdir -p "`dirname "${DESTDIR}${cache_file}"`"
            cp "${cache_file}" "${DESTDIR}${cache_file}"
        fi
    done

    # TPM tools
    if $TPM
    then
        rm -f ${DESTDIR}/bin/tcsd
        rm -f ${DESTDIR}/bin/tpm_unsealdata

        copy_exec /usr/bin/tpm_unsealdata /bin/tpm_unsealdata
        copy_exec /usr/sbin/tcsd /bin/tcsd

        mkdir -p ${DESTDIR}/var/lib/tpm
        cp /var/lib/tpm/system.data ${DESTDIR}/var/lib/tpm/system.data

        getent passwd tss >> ${DESTDIR}/var/lib/tpm/passwd
        getent group tss >> ${DESTDIR}/var/lib/tpm/group
    fi

    # DNS
    rm -f ${DESTDIR}/etc/hosts
    cp /etc/hosts ${DESTDIR}/etc/hosts

    # FSTAB
    rm -f ${DESTDIR}/etc/fstab
    cp /etc/fstab ${DESTDIR}/etc/fstab

fi
