verbose=boolean(default=False)
ip=option("4","6","all", default="all")
server=string()
random_server=boolean(default=True)
server_rescue=string(default="")
check_certificate=boolean(default=True)
ca_certificate_file=string(default="/etc/ssl/certs/ca-certificates.crt")
timeout=integer(default=60)
try=integer(default=1)
interval=integer(default=60)
use_proxy_env=boolean(default=False)
private_key=string(default="/var/lib/ntbclient/key.pem")
public_key=string(default="/var/lib/ntbclient/key-pub.pem")
id=string(default="")
id_file=string(default="/sys/class/dmi/id/product_uuid")
cache_id_file=string(default="/var/lib/ntbclient/cache_id")
