#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

. /scripts/functions

[ -r /var/run/ntbclient.pid ] || exit 0

log_begin_msg "Stopping ntbclient"

[ -f "/etc/default/ntbclient" ] && . /etc/default/ntbclient
case `echo "${USE_TPM}" | cut -c 1` in
    T|t|Y|y)
        TPM=true;;
    *)
        TPM=false;;
esac
REBOOT=false
case `echo "${REBOOT_AFTER_TIME}" | cut -c 1` in
    T|t|Y|y)
        REBOOT=true;;
    *)
        REBOOT=false;;
esac

if ${REBOOT}
then
    kill "$(cat /var/run/ntbclient_reboot.pid)"
fi

if ${TPM}
then
    killall tcsd > /dev/null 2>&1
fi

kill "$(cat /var/run/ntbclient.pid)"

umount /boot

case `echo "${CLEAN_NETWORK}" | cut -c 1` in
    T|t|Y|y)
        CLEAN=true;;
    *)
        CLEAN=false;;
esac

if ${CLEAN}
then
    # From /usr/share/initramfs-tools/scripts/functions
    # -> configure_networking()
    # Ip-Config tries to create this file and when it succeds
    # creating the file /run/net-"${DEVICE}".conf
    for DEVICE in ` ls /run/net-*.conf /run/net6-*.conf 2> /dev/null | sed "s@^/run/net-@@ ; s/.conf$//" `
    do
        ip addr flush dev "${DEVICE}"
    done
fi

log_end_msg
